name: 'nix-action'

description: 'Install nix and haqq caches'

inputs:
  signingKey:
    description: "haqq cachix key"
    required: true
  extraPullNames:
    description: "comma-separated extra cachix caches"
    required: false
  useMagicNixCache:
    description: "use DeterminateSystems's magic nix cache. If enabled, cachix is disabled"
    required: false
    default: false
  useCacheNixAction:
    description: "use nix-community/cache-nix-action"
    required: false
    default: true
  installDevenv:
    description: "install devenv profile"
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - uses: nixbuild/nix-quick-install-action@v26
    - name: Setup cache-nix-action
      if: ${{ inputs.useCacheNixAction == 'true' }}
      uses: nix-community/cache-nix-action@v5
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
        # restore a cache by this prefix
        restore-prefixes-first-match: nix-${{ runner.os }}-
        # collect garbage until Nix store size (in bytes) is at most this number
        # before trying to save a new cache
        gc-max-store-size-linux: 1073741824
        # do purge caches
        purge: true
        # purge all versions of the cache
        purge-prefixes: cache-${{ matrix.os }}-
        # created more than this number of seconds ago relative to the start of the `Post Restore` phase
        purge-created: 0
        # except the version with the `primary-key`, if it exists
        purge-primary-key: never
    - name: Setup cachix
      if: ${{ inputs.useMagicNixCache != 'true' }}
      uses: cachix/cachix-action@v14
      with:
        name: haqq
        signingKey: ${{ inputs.signingKey }}
        extraPullNames: ${{ inputs.extraPullNames }}
    - name: Setup magic nix cache
      if: ${{ inputs.useMagicNixCache == 'true' }}
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv
      if: ${{ inputs.installDevenv == 'true' }}
      run: nix profile install --accept-flake-config --extra-substituters https://nix-community.cachix.org tarball+https://install.devenv.sh/latest
      shell: bash
