name: 'nix-action'

description: 'Install nix and haqq caches'

inputs:
  signingKey:
    description: "haqq cachix key"
    required: true
  extraPullNames:
    description: "comma-separated extra cachix caches"
    required: false
  useMagicNixCache:
    description: "use DeterminateSystems's magic nix cache. If enabled, cachix is disabled"
    required: false
    default: false
  installDevenv:
    description: "install devenv profile"
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Setup cachix
      if: ${{ inputs.useMagicNixCache != 'true' }}
      uses: cachix/cachix-action@v14
      with:
        name: haqq
        signingKey: ${{ inputs.signingKey }}
        extraPullNames: ${{ inputs.extraPullNames }}
    - name: Setup magic nix cache
      if: ${{ inputs.useMagicNixCache == 'true' }}
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv
      if: ${{ inputs.installDevenv == 'true' }}
      run: nix profile install --accept-flake-config --extra-substituters https://nix-community.cachix.org tarball+https://install.devenv.sh/latest
      shell: bash
