name: 'nix-action'

description: 'Install nix and haqq caches'

inputs:
  signingKey:
    description: 'haqq cachix key'
    required: true
  extraPullNames:
    description: 'comma-separated extra cachix caches'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: haqq
        signingKey: ${{ inputs.signingKey }}
        extraPullNames: ${{ inputs.extraPullNames }}
